// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vchip_tb.h for the primary calling header

#ifndef VERILATED_VCHIP_TB___024ROOT_H_
#define VERILATED_VCHIP_TB___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vchip_tb__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vchip_tb___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ chip_tb__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__hrstn;
        CData/*0:0*/ chip_tb__DOT__itcm_ready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__hrstn;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_ready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_hwrite;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_hsize;
        CData/*6:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_hprot;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_hburst;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_htrans;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_hmastlock;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_hready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_hresp;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_hwrite;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_hsize;
        CData/*6:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_hprot;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_hburst;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_htrans;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_hmastlock;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_hready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_hresp;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hrstn;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hwrite;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hsize;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hburst;
        CData/*6:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hprot;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__htrans;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hresp;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hburst_error;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hsize_error;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__haddr_error;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__trans_error;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hrstn;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hwrite;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hsize;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hburst;
        CData/*6:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hprot;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__htrans;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hresp;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hburst_error;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hsize_error;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__haddr_error;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__trans_error;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__hrstn;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_hwrite;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_hsize;
        CData/*6:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_hprot;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_hburst;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_htrans;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_hmastlock;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_hready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_hresp;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_hwrite;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_hsize;
        CData/*6:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_hprot;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_hburst;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_htrans;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_hmastlock;
    };
    struct {
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_hready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_hresp;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_ready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_idle;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__pc_write;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_lui;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_auipc;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_jal;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_jalr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_beq;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_bne;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_blt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_bge;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_bltu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_bgeu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_lb;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_lh;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_lw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_lbu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_lhu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_sb;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_sh;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_sw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_addi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_slti;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_sltiu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_xori;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_ori;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_andi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_slli;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_srli;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_srai;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_add;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_sub;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_sll;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_slt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_sltu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_xor;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_srl;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_sra;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_or;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_and;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_fence;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_fence_i;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_ecall;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_ebreak;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_csrrw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_csrrs;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_csrrc;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_csrrwi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_csrrsi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_csrrci;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_upper_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_imm_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_reg_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_jump_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_branch_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_load_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_store_en;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_rs2;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_rs1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_rd;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_rd;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_sext;
    };
    struct {
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_size;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_en;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_store_size;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_store_en;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_load_rd;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_load_en;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__reg_wen;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__reg_raddr_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__reg_ren_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_dec_stall;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__hrstn;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__reg_wen;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__reg_raddr_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__reg_ren_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hrstn;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hwrite;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hsize;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hburst;
        CData/*6:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hprot;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__htrans;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hmastlock;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hresp;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__itcm_ready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__ifu_idle;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__ifu_dec_stall;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__pc_write;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__state;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__nextstate;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__ifu_dec_stall;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_lui;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_auipc;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_jal;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_jalr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_beq;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_bne;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_blt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_bge;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_bltu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_bgeu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_lb;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_lh;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_lw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_lbu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_lhu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_sb;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_sh;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_sw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_addi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_slti;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_sltiu;
    };
    struct {
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_xori;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_ori;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_andi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_slli;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_srli;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_srai;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_add;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_sub;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_sll;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_slt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_sltu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_xor;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_srl;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_sra;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_or;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_and;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_fence;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_fence_i;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_ecall;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_ebreak;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_csrrw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_csrrs;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_csrrc;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_csrrwi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_csrrsi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_csrrci;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_upper_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_imm_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_reg_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_jump_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_branch_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_load_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_store_en;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_rs2;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_rs1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_rd;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_31_28;
        CData/*6:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_31_25;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_19_15;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_14_12;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_11_7;
        CData/*6:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_31_28_equal_0000;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_19_15_equal_00000;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_11_7_equal_00000;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_31_25_equal_0000000;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_31_25_equal_0100000;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_14_12_equal_000;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_14_12_equal_001;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_14_12_equal_010;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_14_12_equal_011;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_14_12_equal_100;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_14_12_equal_101;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_14_12_equal_110;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_14_12_equal_111;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_0000011;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_0001111;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_0010011;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_0010111;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_0100011;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_0110011;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_0110111;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_1100011;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_1100111;
    };
    struct {
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_1101111;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_6_0_equal_1110011;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_31_20_equal_000000000000;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_31_20_equal_000000000001;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_lui;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_auipc;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_jal;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_jalr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_beq;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_bne;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_blt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_bge;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_bltu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_bgeu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_lb;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_lh;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_lw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_lbu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_lhu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_sb;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_sh;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_sw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_addi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_slti;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_sltiu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_xori;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_ori;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_andi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_csrrw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_csrrs;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_csrrc;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_csrrwi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_csrrsi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_csrrci;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_slli;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_srli;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_srai;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_add;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_sub;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_sll;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_slt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_sltu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_xor;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_srl;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_sra;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_or;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_and;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_fence;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_fence_i;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_ecall;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__mid_ebreak;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT____VdfgTmp_hc00f64ab__0;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT____VdfgTmp_h4745dcb5__0;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT____VdfgTmp_h615169f4__0;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT____VdfgTmp_h230ed8e8__0;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ifu_dec_stall;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_lui;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_auipc;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_jal;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_jalr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_beq;
    };
    struct {
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_bne;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_blt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_bge;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_bltu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_bgeu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_lb;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_lh;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_lw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_lbu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_lhu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_sb;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_sh;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_sw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_addi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_slti;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_sltiu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_xori;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_ori;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_andi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_slli;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_srli;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_srai;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_add;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_sub;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_sll;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_slt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_sltu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_xor;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_srl;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_sra;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_or;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_and;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_fence;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_fence_i;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_ecall;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_ebreak;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_csrrw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_csrrs;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_csrrc;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_csrrwi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_csrrsi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_csrrci;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_upper_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_imm_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_reg_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_jump_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_branch_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_load_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_store_en;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_rs2;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_rs1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_rd;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__pc_write;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_rd;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_sext;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_size;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_en;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_size;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_en;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__reg_wen;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__reg_raddr_2;
    };
    struct {
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__reg_ren_2;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__flush;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__flush_stall;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_stall;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT____Vcellinp__exu_upper_en_inst__dec_upper_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT____Vcellinp__ex_imm_en_inst__dec_branch_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT____Vcellinp__exu_load_swc_inst__dec_load_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__pc_write__en15;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__pc_write__en23;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__dec_upper_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__dec_lui;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__dec_auipc;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__dec_rd;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__reg_wen;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__exu_stall;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__mid_reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__mid_reg_wen;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_branch_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_addi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_slti;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_sltiu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_xori;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_ori;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_andi;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_slli;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_srli;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_srai;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_rd;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_rs1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__reg_wen;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__mid_reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__mid_reg_wen;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__mid_reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__mid_reg_ren_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_add;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_sub;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_sll;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_slt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_sltu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_xor;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_srl;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_sra;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_or;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_and;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_rs1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_rs2;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__dec_rd;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__reg_wen;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__reg_raddr_1;
    };
    struct {
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__reg_raddr_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__reg_ren_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__exu_stall;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__mid_reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__mid_reg_wen;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__mid_reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__mid_reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__mid_reg_raddr_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__mid_reg_ren_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__dec_jump_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__dec_jal;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__dec_jalr;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__dec_rd;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__dec_rs1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__pc_write;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__flush;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__reg_wen;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__mid_reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__mid_reg_wen;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__mid_reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__mid_reg_ren_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__mid_pc_write;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__mid_flush;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__dec_branch_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__dec_beq;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__dec_bne;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__dec_blt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__dec_bge;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__dec_bltu;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__dec_bgeu;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__dec_rs1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__dec_rs2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__pc_write;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__flush;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__reg_raddr_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__reg_ren_2;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__mid_reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__mid_reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__mid_reg_raddr_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__mid_reg_ren_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__mid_pc_write;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__branch;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__mid_flush;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__ifu_dec_stall;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__dec_load_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__dec_lb;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__dec_lh;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__dec_lw;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__dec_lbu;
    };
    struct {
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__dec_lhu;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__dec_rd;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__dec_rs1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_rd;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_sext;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_size;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_en;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__mid_reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__mid_reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_rd_buff;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_sext_buff;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_size_buff;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_en_buff;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__cycle_cnt;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__dec_store_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__dec_sb;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__dec_sh;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__dec_sw;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__dec_rs1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__dec_rs2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__exu_store_en;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__exu_store_size;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__reg_raddr_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__reg_ren_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__exu_stall;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__mid_reg_raddr_1;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__mid_reg_ren_1;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__mid_reg_raddr_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__mid_reg_ren_2;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__exu_store_en_buff;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__exu_store_size_buff;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__cycle_cnt;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__flush;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__flush_stall;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__state;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__nextstate;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hrstn;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hwrite;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hsize;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hburst;
        CData/*6:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hprot;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__htrans;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hmastlock;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hready;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hresp;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__cycle_cnt;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__exu_load_rd;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__exu_load_sext;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__exu_load_size;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__exu_load_en;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__exu_store_en;
        CData/*1:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__exu_store_size;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__mau_load_rd;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__mau_load_en;
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__state;
    };
    struct {
        CData/*2:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__nextstate;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__mau_load_rd_buff;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__hclk;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__hrstn;
        CData/*3:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__cycle_cnt;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__mau_load_rd;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__mau_load_en;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__reg_wen;
        CData/*4:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__mid_reg_waddr;
        CData/*0:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__mid_reg_wen;
        CData/*4:0*/ __Vdly__chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_rd;
        CData/*0:0*/ __Vdly__chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_sext;
        CData/*1:0*/ __Vdly__chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_size;
        CData/*0:0*/ __Vdly__chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_en;
        CData/*0:0*/ __Vtrigprevexpr___TOP__chip_tb__DOT__hclk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__chip_tb__DOT__hrstn__0;
        CData/*0:0*/ __VactContinue;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_imm_type_i;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_imm_type_s;
        SData/*12:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_imm_type_b;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_imm_type_i;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_imm_type_s;
        SData/*12:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_imm_type_b;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_31_20;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_imm_type_i;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_imm_type_s;
        SData/*12:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_imm_type_b;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__dec_imm_type_i;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__dec_imm_type_i;
        SData/*12:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__dec_imm_type_b;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__dec_imm_type_i;
        SData/*11:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__dec_imm_type_s;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_haddr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_hwdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_hrdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_haddr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_hwdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_hrdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__haddr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hwdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__hrdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__i;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__haddr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hwdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__hrdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__i;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_haddr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_hwdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__itcm_hrdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_haddr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_hwdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dtcm_hrdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__inst_ifu_out;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__pc_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__pc;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__inst_dec_out;
        IData/*19:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_imm_type_u;
        IData/*20:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_imm_type_j;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__inst_exu_out;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_base_addr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_offset;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_store_addr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_store_data;
    };
    struct {
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_load_data;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__reg_rdata_1;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__reg_rdata_2;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__reg_rdata_1;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__reg_rdata_2;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__i;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__haddr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hwdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__hrdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__pc_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__pc;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__inst_out;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__inst_out_buff;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_in;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__inst_out;
        IData/*19:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_imm_type_u;
        IData/*20:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__dec_swc_inst__DOT__dec_imm_type_j;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__inst_in;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__inst_out;
        IData/*19:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_imm_type_u;
        IData/*20:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__dec_imm_type_j;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__pc;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__pc_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_base_addr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_offset;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_addr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_data;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__reg_rdata_1;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__reg_rdata_2;
        IData/*19:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__dec_imm_type_u;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__pc;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_upper_en_inst__DOT__mid_reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__pc;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__reg_rdata_1;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_imm_en_inst__DOT__mid_reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__pc;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__reg_rdata_1;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__reg_rdata_2;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_reg_swc_inst__DOT__mid_reg_wdata;
        IData/*20:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__dec_imm_type_j;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__pc;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__pc_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__reg_rdata_1;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__mid_reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__mid_pc_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__sext_imm_type_j;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__sext_imm_type_i;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__pc_real;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__pc_next;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__pc;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__pc_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__reg_rdata_1;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__reg_rdata_2;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__mid_pc_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__sext_imm_type_b;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__pc_real;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__pc_next;
    };
    struct {
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_base_addr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_offset;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__reg_rdata_1;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_base_addr_buff;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__exu_load_offset_buff;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__exu_store_addr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__exu_store_data;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__reg_rdata_1;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__reg_rdata_2;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__exu_store_addr_buff;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__exu_store_data_buff;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__haddr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hwdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__hrdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__exu_load_base_addr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__exu_load_offset;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__exu_store_addr;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__exu_store_data;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__mau_load_data;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__mau_load_data_buff;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__mau_load_data;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__reg_wdata;
        IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__wbu_swc_inst__DOT__mid_reg_wdata;
        IData/*31:0*/ __Vdly__chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_base_addr;
        IData/*31:0*/ __Vdly__chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_load_offset;
        IData/*31:0*/ __Vdly__chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_store_data;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*7:0*/, 4096> chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__sram;
        VlUnpacked<CData/*7:0*/, 4096> chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__sram;
        VlUnpacked<IData/*31:0*/, 32> chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__regfile_swc_inst__DOT__regfile;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vchip_tb__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr VlWide<5>/*159:0*/ chip_tb__DOT__ITCM_DATA_PATH = {{
        0x2e747874, 0x6c696e6b, 0x726f6d5f, 0x6669672f,
        0x2e636f6e
    }};
    static constexpr VlWide<5>/*159:0*/ chip_tb__DOT__DTCM_DATA_PATH = {{
        0x2e747874, 0x6c696e6b, 0x726f6d5f, 0x6669672f,
        0x2e636f6e
    }};
    static constexpr VlWide<5>/*159:0*/ chip_tb__DOT__chip_top_inst__DOT__ITCM_DATA_PATH = {{
        0x2e747874, 0x6c696e6b, 0x726f6d5f, 0x6669672f,
        0x2e636f6e
    }};
    static constexpr VlWide<5>/*159:0*/ chip_tb__DOT__chip_top_inst__DOT__DTCM_DATA_PATH = {{
        0x2e747874, 0x6c696e6b, 0x726f6d5f, 0x6669672f,
        0x2e636f6e
    }};
    static constexpr VlWide<5>/*159:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__DATA_PATH = {{
        0x2e747874, 0x6c696e6b, 0x726f6d5f, 0x6669672f,
        0x2e636f6e
    }};
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__SRAM_SIZE = 0x00001000U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__HTRANS_IDLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__HTRANS_BUSY = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__HTRANS_NONSEQ = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__itcm_swc_inst__DOT__HTRANS_SEQ = 3U;
    static constexpr VlWide<5>/*159:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__DATA_PATH = {{
        0x2e747874, 0x6c696e6b, 0x726f6d5f, 0x6669672f,
        0x2e636f6e
    }};
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__SRAM_SIZE = 0x00001000U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__HTRANS_IDLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__HTRANS_BUSY = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__HTRANS_NONSEQ = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__dtcm_swc_inst__DOT__HTRANS_SEQ = 3U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__HTRANS_IDLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__HTRANS_BUSY = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__HTRANS_NONSEQ = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__HTRANS_SEQ = 3U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__IDLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__START = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__WAIT1 = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__ifu_swc_inst__DOT__WAIT2 = 3U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__FLUSH_DISABLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__FLUSH_CYCLE_1 = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_jump_swc_inst__DOT__FLUSH_CYCLE_2 = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__FLUSH_DISABLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__FLUSH_CYCLE_1 = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_branch_swc_inst__DOT__FLUSH_CYCLE_2 = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__LOAD_IDLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__LOAD_BTYE = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__LOAD_HALFWORD = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_load_swc_inst__DOT__LOAD_WORD = 3U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__STORE_BTYE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__STORE_HALFWORD = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__STORE_WORD = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__exu_store_swc_inst__DOT__STORE_IDLE = 3U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__FLUSH_DISABLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__FLUSH_CYCLE_1 = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__FLUSH_CYCLE_2 = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__IDLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__STATE_1 = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__exu_top_swc_inst__DOT__ex_flush_swc_inst__DOT__STATE_2 = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__HTRANS_IDLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__HTRANS_BUSY = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__HTRANS_NONSEQ = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__HTRANS_SEQ = 3U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__IDLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__READ_START = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__READ_WAIT1 = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__READ_WAIT2 = 3U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__WRITE_START = 4U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__WRITE_WAIT = 5U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__CNT_MAX = 4U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__LOAD_IDLE = 0U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__LOAD_BTYE = 1U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__LOAD_HALFWORD = 2U;
    static constexpr IData/*31:0*/ chip_tb__DOT__chip_top_inst__DOT__core_top_swc_inst__DOT__mau_swc_inst__DOT__LOAD_WORD = 3U;

    // CONSTRUCTORS
    Vchip_tb___024root(Vchip_tb__Syms* symsp, const char* v__name);
    ~Vchip_tb___024root();
    VL_UNCOPYABLE(Vchip_tb___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
