#!/usr/bin/env python3
import argparse
import os

def binary_file_to_hex_txt(input_file, output_file):
    with open(input_file, 'rb') as f:
        binary_data = f.read()

    hex_data = '\n'.join(' '.join(format(byte, '02X') for byte in binary_data[i:i+4]) for i in range(0, len(binary_data), 4))

    hex_data += '\n'

    with open(output_file, 'w') as f:
        f.write(hex_data)
        print(f"Output saved to {output_file}")

def main():
    parser = argparse.ArgumentParser(description="Convert a binary file to a hexadecimal text file.")
    parser.add_argument("input_file", help="Path to the input binary file.")
    args = parser.parse_args()

    input_path = args.input_file
    directory = os.path.dirname(input_path)
    output_path = os.path.join(directory, "rom.txt")
    
    binary_file_to_hex_txt(input_path, output_path)

if __name__ == "__main__":
    main()
